// test/report-type-status-dependency.test.js
//
// Covers all 12 requirements from the 2026-10-05 "Report Type and Status Field
// Dependency" feature request:
//   1.  Summary enables Status selection (backend: user-supplied status respected)
//   2.  Active disables Status selection (backend: implied status is authoritative)
//   3.  Expired disables Status selection
//   4.  Inactive disables Status selection
//   5.  Expiring Soon disables Status selection
//   6.  Switching back to Summary re-enables Status selection (status filter works)
//   7.  Stale status value cannot create conflicting report results
//   8.  Comparison fields follow the same rules independently
//   9.  Mid-Year Report and Yearly Output Report absent from Comparison Report Type
//  10.  Primary Report Type options unchanged
//  11.  Report generation uses correct filters (comparison result correctness)
//  12.  Existing date/country/grouping/export filters still work

const fs      = require('fs');
const path    = require('path');
const request = require('supertest');
const app     = require('../cirl');
const { connectDB, closeDB } = require('../db');
const { createTestUser, loginAs, cleanupAll } = require('./helpers');

// ─── helpers ──────────────────────────────────────────────────────────────────
const read = (...p) => fs.readFileSync(path.join(__dirname, '..', ...p), 'utf8');
const view = read('views', 'administrator', 'reports.ejs');
const fmt  = (d) => d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
const days = (n) => { const d = new Date(); d.setDate(d.getDate() + n); return d; };

// ─── static (view-file) tests ─────────────────────────────────────────────────
describe('9 & 10 — Comparison Report Type options (static view check)', () => {

  test('9a. Mid-Year Report is NOT present in the Comparison Report Type dropdown', () => {
    // The comparison card HTML is generated by renderConfigCardHtml().
    // "Mid-Year Report" must not appear as a selectable option value in that function.
    const fn = view.slice(
      view.indexOf('function renderConfigCardHtml'),
      view.indexOf('function onCmpReportTypeChange')
    );
    // The option text "Mid-Year Report" and value "Mid-Year" must both be absent
    expect(fn).not.toMatch(/Mid-Year Report/);
    expect(fn).not.toMatch(/value="Mid-Year"/);
  });

  test('9b. Yearly Output Report is NOT present in the Comparison Report Type dropdown', () => {
    const fn = view.slice(
      view.indexOf('function renderConfigCardHtml'),
      view.indexOf('function onCmpReportTypeChange')
    );
    expect(fn).not.toMatch(/Yearly Output Report/);
    expect(fn).not.toMatch(/value="Yearly"/);
  });

  test('10. Primary Report Type dropdown still has all required options', () => {
    // Inspect the HTML block that defines #cr-type
    const typeBlock = view.slice(
      view.indexOf('id="cr-type"'),
      view.indexOf('</select>', view.indexOf('id="cr-type"')) + 9
    );
    expect(typeBlock).toMatch(/value="Summary"/);
    expect(typeBlock).toMatch(/value="Active Partnerships"/);
    expect(typeBlock).toMatch(/value="Inactive Partnerships"/);
    expect(typeBlock).toMatch(/value="Expired Partnerships"/);
    expect(typeBlock).toMatch(/value="Expiring Soon"/);
  });

  test('STATUS_TYPED_REPORT_TYPES covers all four non-Summary types', () => {
    const jsBlock = view.slice(
      view.indexOf('var STATUS_TYPED_REPORT_TYPES'),
      view.indexOf('var STATUS_TYPED_REPORT_TYPES') + 300
    );
    expect(jsBlock).toBeTruthy();
    // Verify the list is derived from REPORT_TYPE_IMPLIED_STATUS
    expect(jsBlock).toMatch(/Object\.keys\(REPORT_TYPE_IMPLIED_STATUS\)/);
  });

  test('onReportTypeChange calls applyStatusFieldState', () => {
    const fn = view.slice(
      view.indexOf('function onReportTypeChange'),
      view.indexOf('function onReportTypeChange') + 300
    );
    expect(fn).toMatch(/applyStatusFieldState/);
    expect(fn).toMatch(/cr-status-hint/);
    expect(fn).toMatch(/cr-status-col/);
  });

  test('onCmpReportTypeChange function exists and references STATUS_TYPED_REPORT_TYPES', () => {
    expect(view).toMatch(/function onCmpReportTypeChange/);
    const fn = view.slice(
      view.indexOf('function onCmpReportTypeChange'),
      view.indexOf('function onCmpReportTypeChange') + 600
    );
    expect(fn).toMatch(/STATUS_TYPED_REPORT_TYPES/);
    expect(fn).toMatch(/statusEl\.disabled/);
    expect(fn).toMatch(/statusEl\.value = ''/);
  });

  test('Comparison card Report Type select has onchange="onCmpReportTypeChange(...)"', () => {
    const fn = view.slice(
      view.indexOf('function renderConfigCardHtml'),
      view.indexOf('function onCmpReportTypeChange')
    );
    expect(fn).toMatch(/onchange="onCmpReportTypeChange\(/);
  });

  test('Comparison card Status select has disabled attribute logic', () => {
    const fn = view.slice(
      view.indexOf('function renderConfigCardHtml'),
      view.indexOf('function onCmpReportTypeChange')
    );
    expect(fn).toMatch(/statusDisabledAttr/);
    expect(fn).toMatch(/cr-status-disabled/);
  });

  test('Primary Status field has id=cr-status-col on its column and a hint div', () => {
    // id="cr-status-col" on the wrapping div
    expect(view).toMatch(/id="cr-status-col"/);
    // hint div
    expect(view).toMatch(/id="cr-status-hint"/);
  });
});

// ─── backend tests ────────────────────────────────────────────────────────────
describe('1–8 & 11–12 — Backend: Report Type controls effective status filter', () => {
  let agent;
  let ids = [];
  const TAG  = `JestStatusDep ${Date.now()}`;

  jest.setTimeout(60000);

  beforeAll(async () => {
    const db = await connectDB();
    agent = request.agent(app);
    await loginAs(agent, await createTestUser({ role: 'Administrator' }));

    // Use a random base in the 820000–919999 range so parallel test files
    // cannot collide on the same numeric IDs (real sequential IDs are far
    // below this range and the window is large enough to avoid cross-file
    // overlap even when multiple test files run simultaneously).
    const base = 820000 + Math.floor(Math.random() * 100000);

    const fixtures = [
      { id: base,     inst: `${TAG} Active`,       status: 'Active',   start: fmt(days(-10)),  end: fmt(days(400)),  country: 'Japan',        type: 'MOA', cat: 'International', unit: ['CCS'] },
      { id: base + 1, inst: `${TAG} Expired`,      status: 'Active',   start: fmt(days(-800)), end: fmt(days(-10)),  country: 'Japan',        type: 'MOU', cat: 'International', unit: ['CILS'] },
      { id: base + 2, inst: `${TAG} Inactive`,     status: 'Inactive', start: fmt(days(-200)), end: fmt(days(-50)),  country: 'Philippines',  type: 'MOA', cat: 'Local',          unit: ['CIRL'] },
      { id: base + 3, inst: `${TAG} ExpiringSoon`, status: 'Active',   start: fmt(days(-300)), end: fmt(days(20)),   country: 'Philippines',  type: 'MOU', cat: 'Local',          unit: ['CCS'] }
    ];
    ids = fixtures.map(f => f.id);
    await db.collection('partnerships').insertMany(fixtures.map(f => ({ ...f, remarks: 'jeststatustest' })));
  });

  afterAll(async () => {
    const db = await connectDB();
    await db.collection('partnerships').deleteMany({ id: { $in: ids } });
    await cleanupAll();
    await closeDB();
  });

  const mine = (records) => (records || []).filter(p => p.inst && p.inst.startsWith(TAG));

  // 1. Summary + explicit status filter → user's choice is respected
  test('1. Summary respects the explicit Status filter (Active only)', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({ reportType: 'Summary', status: 'Active', inst: TAG });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    // All my fixtures that are effectively Active (computeStatusFromEnd):
    // "Active" record: end +400 → Active ✓
    // "Expired" record: end -10 → Expired ✗ (filtered out)
    // "Inactive" record: status Inactive ✗
    // "ExpiringSoon" record: end +20 → Expiring Soon ✗
    expect(myRecs.length).toBe(1);
    expect(myRecs[0].inst).toBe(`${TAG} Active`);
  });

  // 2. Active Partnerships → implied Active, user-supplied Expired is IGNORED
  test('2. Active Partnerships: implied status wins even if status=Expired is supplied', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Active Partnerships', status: 'Expired', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    // Only the Active record should appear; the Expired filter is ignored
    expect(myRecs.every(p => p.status === 'Active')).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Active`)).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Expired`)).toBe(false);
  });

  // 3. Expired Partnerships → implied Expired, user-supplied Active is IGNORED
  test('3. Expired Partnerships: implied status wins even if status=Active is supplied', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Expired Partnerships', status: 'Active', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    expect(myRecs.every(p => p.status === 'Expired')).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Expired`)).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Active`)).toBe(false);
  });

  // 4. Inactive Partnerships → implied Inactive, user-supplied Active is IGNORED
  test('4. Inactive Partnerships: implied status wins even if status=Active is supplied', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Inactive Partnerships', status: 'Active', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    // Inactive status filter includes Inactive and Expired records
    expect(myRecs.some(p => p.inst === `${TAG} Inactive`)).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Active`)).toBe(false);
  });

  // 5. Expiring Soon → implied Expiring Soon, user-supplied Expired is IGNORED
  test('5. Expiring Soon: implied status wins even if status=Expired is supplied', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Expiring Soon', status: 'Expired', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    expect(myRecs.every(p => p.status === 'Expiring Soon')).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} ExpiringSoon`)).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Expired`)).toBe(false);
  });

  // 6. Switching back to Summary — Status filter is re-applied correctly
  test('6. Summary after switching: user-supplied status filter is respected again', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Summary', status: 'Inactive', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    expect(myRecs.some(p => p.inst === `${TAG} Inactive`)).toBe(true);
    expect(myRecs.some(p => p.inst === `${TAG} Active`)).toBe(false);
  });

  // 7. Stale status value cannot create contradictory results
  test('7. Stale status=Inactive cannot override Active Partnerships report type', async () => {
    // Simulates a stale status value from a previous Summary+Inactive selection
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Active Partnerships', status: 'Inactive', inst: TAG
    });
    expect(res.status).toBe(200);
    const myRecs = mine(res.body.records);
    // Must only return Active records — Inactive ones must be excluded
    expect(myRecs.some(p => p.status !== 'Active')).toBe(false);
    expect(res.body.filters.status).toBe('Active');
  });

  // 8. Comparison fields follow the same rules independently
  test('8. Comparison: Active Partnerships config ignores stale status=Expired', async () => {
    const configs = [
      { label: 'A', reportType: 'Active Partnerships', status: 'Expired', inst: TAG },
      { label: 'B', reportType: 'Expired Partnerships', status: 'Active', inst: TAG }
    ];
    const qs = 'configs=' + encodeURIComponent(JSON.stringify(configs));
    const res = await agent.get('/api/reports/comparison/multi/preview?' + qs);
    expect(res.status).toBe(200);

    const resultA = res.body.results.find(r => r.label === 'A');
    const resultB = res.body.results.find(r => r.label === 'B');
    expect(resultA).toBeDefined();
    expect(resultB).toBeDefined();

    // Result A must only have Active records
    const myA = mine(resultA.records);
    expect(myA.every(p => p.status === 'Active')).toBe(true);
    // Result B must only have Expired records
    const myB = mine(resultB.records);
    expect(myB.every(p => p.status === 'Expired')).toBe(true);

    // Filters must reflect correct effective status, not the stale one
    expect(resultA.filters.status).toBe('Active');
    expect(resultB.filters.status).toBe('Expired');
  });

  test('8b. Comparison: Summary config fully respects explicit status filter', async () => {
    const configs = [
      { label: 'C', reportType: 'Summary', status: 'Active', inst: TAG }
    ];
    const qs = 'configs=' + encodeURIComponent(JSON.stringify(configs));
    const res = await agent.get('/api/reports/comparison/multi/preview?' + qs);
    expect(res.status).toBe(200);
    const resultC = res.body.results.find(r => r.label === 'C');
    expect(resultC).toBeDefined();
    const myC = mine(resultC.records);
    expect(myC.every(p => p.status === 'Active')).toBe(true);
    expect(resultC.filters.status).toBe('Active');
  });

  test('8c. Primary and comparison filters are independent (changing primary type does not affect comparison)', async () => {
    // Run a Summary primary report and an Active Partnerships comparison simultaneously
    const primaryRes = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Summary', inst: TAG
    });
    const configs = [{ label: 'CmpOnly', reportType: 'Expired Partnerships', inst: TAG }];
    const cmpRes  = await agent.get('/api/reports/comparison/multi/preview?configs=' + encodeURIComponent(JSON.stringify(configs)));

    // Primary should show all records (no status filter)
    expect(mine(primaryRes.body.records).length).toBe(4);
    // Comparison should show only Expired
    const cmpResult = cmpRes.body.results.find(r => r.label === 'CmpOnly');
    expect(mine(cmpResult.records).every(p => p.status === 'Expired')).toBe(true);
  });

  // 11. Report generation produces the right records (already covered above for primary)
  // Extra: verify filters object is echoed correctly in response
  test('11. Filters echo in response matches the effective status used', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Active Partnerships', inst: TAG
    });
    expect(res.body.filters.reportType).toBe('Active Partnerships');
    expect(res.body.filters.status).toBe('Active');
  });

  // 12. Existing date, country, unit, groupBy filters still work alongside the new logic
  test('12a. Date filter still works with a status-typed report type', async () => {
    // Request Active Partnerships with a date range that excludes all our fixtures
    const farFuture = new Date(); farFuture.setFullYear(farFuture.getFullYear() + 5);
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Active Partnerships',
      dateFrom: farFuture.toISOString().slice(0, 10),
      inst: TAG
    });
    expect(res.status).toBe(200);
    expect(mine(res.body.records).length).toBe(0);
  });

  // 12b & 12c verify the filter MECHANISM, not fixture presence, so they pass
  // regardless of what other test files have inserted in a parallel run.
  test('12b. Country filter correctly scopes results — all returned records match the requested country', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Summary', status: 'Active', country: 'Japan'
    });
    expect(res.status).toBe(200);
    // Every record the API returns must have country === Japan — the filter worked.
    const records = res.body.records || [];
    expect(records.every(p => (p.country || '').toLowerCase() === 'japan')).toBe(true);
  });

  test('12c. Group By filter produces comparison response structure with a status-typed Report Type', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Active Partnerships', groupBy: 'country'
    });
    expect(res.status).toBe(200);
    // groupBy must flip the response into comparison mode with a valid array
    expect(res.body.isComparison).toBe(true);
    expect(Array.isArray(res.body.comparisonData)).toBe(true);
  });

  test('12d. College/Unit filter still works with Summary + status', async () => {
    const res = await agent.get('/api/reports/custom/preview').query({
      reportType: 'Summary', unit: 'CCS', inst: TAG
    });
    expect(res.status).toBe(200);
    // Only CCS fixtures
    expect(mine(res.body.records).every(p => {
      const u = Array.isArray(p.unit) ? p.unit : [p.unit];
      return u.includes('CCS');
    })).toBe(true);
  });
});
