services:
  - type: web
    name: ciprms-cspc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node cirl.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_TOKEN_ENCRYPTION_KEY
        sync: false